### ISSUE TITLE
The aspiration window condition is wrong(?)

### ISSUE THREAD

**Issue by tttony** [Tempate/Achillees#1]
Hi, I recently discovered this engine and notice that this line is wrong? https://github.com/Tempate/Achillees/blob/master/src/search.c#L54, it should be like this? https://web.archive.org/web/20071031095918/http://www.brucemo.com/compchess/programming/aspiration.htm

**Comment by Tempate** [comment]
Hello,
First of all, thank you for your comment. I have tested the patch you suggested and unfortunately it didn't pass. The final score was: 

Score of AchilleesNew vs AchilleesOld: 7 - 39 - 4  [0.180] 50
Elo difference: -263.4 +/- 128.3, LOS: 0.0 %, DrawRatio: 8.0 %

 If I recall correctly I followed that page in one of my first aspiration windows implementations, but switched later to the one I currently have due to an increase on performance. However, if your tests show something different, feel free to share the code so I can try it myself.
Thank you for your interest.

```
int alpha = -INFINITY, beta = INFINITY;
const int delta = 50;

for (int depth = 1; depth <= settings.depth;) {
	const int score = pvSearch(board, depth, alpha, beta, 0);

	if ((score <= alpha) || (score >= beta)) {
		alpha = -INFINITY;
		beta = INFINITY;
		continue;
	}

	alpha = score - delta;
	beta = score + delta;

	if (settings.stop) break;

	bestMove = decompressMove(board, &tt[index].move);

	Move pv[MAX_DEPTH];
	const int nPV = probePV(*board, pv);

	const long duration = 1000 * (clock() - start) / CLOCKS_PER_SEC;
	
	infoString(board, depth, score, stats.nodes, duration, pv, nPV);

	// Stop looking when the fastest mate has been found
	if (abs(score) == MAX_SCORE + depth / 2)
		break;

	depth++;
}
```

**Comment by tempate** [comment]
> Hi, I recently discovered this engine and notice that this line is wrong? https://github.com/Tempate/Achillees/blob/master/src/search.c#L54, it should be like this? https://web.archive.org/web/20071031095918/http://www.brucemo.com/compchess/programming/aspiration.htm

Hello,
First of all, thank you for your comment. I have tested the patch you suggested and unfortunately it didn't pass. The final score was: 

Score of AchilleesNew vs AchilleesOld: 7 - 39 - 4  [0.180] 50
Elo difference: -263.4 +/- 128.3, LOS: 0.0 %, DrawRatio: 8.0 %

 If I recall correctly I followed that page in one of my first aspiration windows implementations, but switched later to the one I currently have due to an increase on performance. However, if your tests show something different, feel free to share the code so I can try it myself.
Thank you for your interest.

```
int alpha = -INFINITY, beta = INFINITY;
const int delta = 50;

for (int depth = 1; depth <= settings.depth;) {
	const int score = pvSearch(board, depth, alpha, beta, 0);

	if ((score <= alpha) || (score >= beta)) {
		alpha = -INFINITY;
		beta = INFINITY;
		continue;
	}

	alpha = score - delta;
	beta = score + delta;

	if (settings.stop) break;

	bestMove = decompressMove(board, &tt[index].move);

	Move pv[MAX_DEPTH];
	const int nPV = probePV(*board, pv);

	const long duration = 1000 * (clock() - start) / CLOCKS_PER_SEC;
	
	infoString(board, depth, score, stats.nodes, duration, pv, nPV);

	// Stop looking when the fastest mate has been found
	if (abs(score) == MAX_SCORE + depth / 2)
		break;

	depth++;
}
```

**Comment by tttony** [comment]
I thought that the Bruce Moreland was the correct way, now I saw three others engines source and they don't use the Bruce version, so is good to know that, my engine is very basic and sometimes I dig it in engine sources

Hope you keep improving your engine
